version: "3.3"

services:
    db:
        container_name: femdb_container
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - femdb:/var/lib/mysql

volumes:
    femdb:
